### ISSUE TITLE
Why Can't this github be cloned?

### ISSUE THREAD

**Issue by overflight620** [intuitive-robots/mdt_policy#10]

**Comment by mbreuss** [comment]
Hi, @overflight620 can you try it again now please?

**Comment by overflight620** [comment]
Now I can clone, but there's a new problem when I run train
![image](https://github.com/user-attachments/assets/82d7dbad-7394-4854-a150-5d0a1cf8a217)
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name           | Type                        | Params
---------------------------------------------------------------
0 | static_resnet  | BesoResNetEncoder           | 11.4 M
1 | gripper_resnet | BesoResNetEncoder           | 11.4 M
2 | gen_img        | MaskedTransformerImgDecoder | 4.0 M 
3 | visual_goal    | DefaultVisionClip           | 149 M 
4 | language_goal  | LangClip                    | 151 M 
5 | model          | GCDenoiser                  | 51.5 M
6 | clip_proj      | ClipStyleProjection         | 0     
---------------------------------------------------------------
78.3 M    Trainable params
300 M     Non-trainable params
379 M     Total params
758.418   Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]pybullet build time: Nov 28 2023 23:51:11
Building EGL_options.o
Error executing job with overrides: []
Traceback (most recent call last):
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "/opt/data/private/VLA/mdt_policy/mdt/wrappers/hulc_wrapper.py", line 18, in __init__
    self.set_egl_device(device)
  File "/opt/data/private/VLA/mdt_policy/mdt/wrappers/hulc_wrapper.py", line 36, in set_egl_device
    egl_id = get_egl_device_id(cuda_id)
  File "/opt/data/private/VLA/mdt_policy/calvin_env/calvin_env/utils/utils.py", line 141, in get_egl_device_id
    result = subprocess.run(["./EGL_options.o"], capture_output=True, cwd=dir_path)
  File "/root/anaconda3/envs/mdt/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/root/anaconda3/envs/mdt/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/root/anaconda3/envs/mdt/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './EGL_options.o'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/opt/data/private/VLA/mdt_policy/mdt/training.py", line 83, in train
    trainer.fit(model, datamodule=datamodule) #, ckpt_path=chk  # type: ignore
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1204, in _run_train
    self._run_sanity_check()
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_sanity_check
    val_loop.run()
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 194, in run
    self.on_run_start(*args, **kwargs)
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 132, in on_run_start
    self._on_evaluation_start()
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 245, in _on_evaluation_start
    self.trainer._call_callback_hooks(hook_name, *args, **kwargs)
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1394, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/opt/data/private/VLA/mdt_policy/mdt/rollout/rollout_long_horizon.py", line 152, in on_validation_start
    self.env = hydra.utils.instantiate(self.env_cfg, dataset, pl_module.device)
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 249, in instantiate_node
    return _call_target(_target_, *args, **kwargs)
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 64, in _call_target
    raise type(e)(
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "/opt/data/private/VLA/mdt_policy/mdt/wrappers/hulc_wrapper.py", line 18, in __init__
    self.set_egl_device(device)
  File "/opt/data/private/VLA/mdt_policy/mdt/wrappers/hulc_wrapper.py", line 36, in set_egl_device
    egl_id = get_egl_device_id(cuda_id)
  File "/opt/data/private/VLA/mdt_policy/calvin_env/calvin_env/utils/utils.py", line 141, in get_egl_device_id
    result = subprocess.run(["./EGL_options.o"], capture_output=True, cwd=dir_path)
  File "/root/anaconda3/envs/mdt/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/root/anaconda3/envs/mdt/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/root/anaconda3/envs/mdt/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: Error instantiating 'mdt.wrappers.hulc_wrapper.HulcWrapper' : [Errno 2] No such file or directory: './EGL_options.o'
python-BaseException
wandb:
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /opt/data/private/VLA/mdt_policy/mdt/wandb/offline-run-20241016_134255-k490f1mh
wandb: Find logs at: wandb/offline-run-20241016_134255-k490f1mh/logs

I don't understand this mistake? I need something extra to configure？

**Comment by overflight620** [comment]
I also tried to debug to fix the error, but [Errno 2] No such file or directory: '. /EGL_options.o'
After python-BaseException solved the error, it reappeared again with a new error：pybullet build time: Nov 28 2023 23:51:11
Error executing job with overrides: []
Traceback (most recent call last):
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "/opt/data/private/VLA/mdt_policy/mdt/wrappers/hulc_wrapper.py", line 18, in __init__
    self.set_egl_device(device)
  File "/opt/data/private/VLA/mdt_policy/mdt/wrappers/hulc_wrapper.py", line 36, in set_egl_device
    egl_id = get_egl_device_id(cuda_id)
  File "/opt/data/private/VLA/mdt_policy/calvin_env/calvin_env/utils/utils.py", line 143, in get_egl_device_id
    n = int(result.stderr.decode("utf-8").split(" of ")[1].split(".")[0])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/data/private/VLA/mdt_policy/mdt/evaluation/mdt_evaluate.py", line 286, in <module>
    main()
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/opt/data/private/VLA/mdt_policy/mdt/evaluation/mdt_evaluate.py", line 239, in main
    model, env, _, lang_embeddings = get_default_beso_and_env(
  File "/opt/data/private/VLA/mdt_policy/mdt/evaluation/utils.py", line 188, in get_default_beso_and_env
    env = hydra.utils.instantiate(rollout_cfg.env_cfg, dataset, device, show_gui=False)
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 249, in instantiate_node
    return _call_target(_target_, *args, **kwargs)
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 64, in _call_target
    raise type(e)(
  File "/root/anaconda3/envs/mdt/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "/opt/data/private/VLA/mdt_policy/mdt/wrappers/hulc_wrapper.py", line 18, in __init__
    self.set_egl_device(device)
  File "/opt/data/private/VLA/mdt_policy/mdt/wrappers/hulc_wrapper.py", line 36, in set_egl_device
    egl_id = get_egl_device_id(cuda_id)
  File "/opt/data/private/VLA/mdt_policy/calvin_env/calvin_env/utils/utils.py", line 143, in get_egl_device_id
    n = int(result.stderr.decode("utf-8").split(" of ")[1].split(".")[0])
IndexError: Error instantiating 'mdt.wrappers.hulc_wrapper.HulcWrapper' : list index out of range
![image](https://github.com/user-attachments/assets/3745847a-769e-4cbc-b16e-2f756b39d0b1)

**Comment by omeryagmurlu** [comment]
Did you follow the setup instructions listed in the readme? I have just tried setting up the repo from scratch and couldn't reproduce your issue.

**Comment by overflight620** [comment]
git clone --recurse-submodules git@github.com:intuitive-robots/mdt_policy.git
The main thing is that this command can't recursively clone the other github code inside, causing me to manually clone the other required code

**Comment by overflight620** [comment]
![image](https://github.com/user-attachments/assets/3ce4da77-23dd-4270-aa78-8e6d7ca189aa)
I can't understand it, I now switch to become a cloud platform and then use the steps on the readme in full, but still get this error, but I can't understand why, exactly!

**Comment by overflight620** [comment]
May I ask what kind of graphics card you are using, because if you need to use EGL's graphics library, I'm not sure if it's the kind of graphics card or the system itself lacks certain rendering libraries, are you using the A100? I'm using A6000. I'm using https://github.com/mees/calvin evaluation from scratch and have the same problem as below
![image](https://github.com/user-attachments/assets/2bb4b0e2-21a0-4b1b-875b-2e0384ced992)

**Comment by omeryagmurlu** [comment]
We have used both A100 and A6000 for training, you can see how the GPU usage looks like on 4 A6000 gpus here: https://github.com/intuitive-robots/mdt_policy/issues/6#issuecomment-2330936317
